// Bilingual content for the portfolio.
const CONTENT = {
  en: {
    nav: ["Work", "Method", "Experience", "About", "Contact"],
    navLabels: { work: "Work", method: "Method", experience: "Experience", about: "About", contact: "Contact" },
    hero: {
      eyebrow: "AI Image Tutor  ·  AI Visual Content Specialist",
      nameFirst: "Kaylee",
      nameLast: "Oh",
      nameScript: "Hakyoung Oh",
      tagline: ["I'm not just an AI", "image creator."],
      taglineAccent: "I teach AI to see.",
      sub: "Production-scale visual judgment for generative pipelines — diagnosing why an image fails, then turning that diagnosis into prompts, models, and tools that don't.",
      meta: [["Based in", "Seoul, KR"], ["Available for", "xAI Image Tutor"], ["Since", "2023"]],
      cta: "See selected work",
      cta2: "Download résumé (PDF)",
    },
    marquee: ["Stable Diffusion","ComfyUI","LoRA","OpenPose","ControlNet","PixAI","Midjourney","NanoBanana","GPT Image","Photoshop","Figma","Notion"],
    about: {
      kicker: "(01) About",
      title: "An artist's eye, with engineering literacy.",
      body: [
        "I work where visual judgment meets AI image generation. Since 2023 — shortly after Stable Diffusion went mainstream — I've operated as an Image Tutor and QA specialist for AI-assisted webtoon and game-content pipelines.",
        "Illustrators are easy to find. AI image creators are increasingly common. What is rare: people who can evaluate generative outputs at production scale, diagnose why an image fails, and translate that diagnosis into structured feedback for prompts, models, controls, and workflows. That's the seat I sit in.",
        "I've sold visual products, generated revenue from them, and led production teams. So when a feedback note like \"this looks too North-American-cartoon, it needs to read more like Japanese anime\" lands on the table — I can decompose the difference into concrete, repeatable, prompt-and-pipeline-level criteria.",
      ],
      stats: [
        ["112.2K+", "Conversations on a single AI-game work"],
        ["716", "Creators who bought my 3D assets"],
        ["1,008", "Resources in the shared archive I built at RIDI"],
        ["230%", "Background-team productivity lift at RIDI"],
        ["50+", "Emotions in my expression dictionary"],
        ["5", "Successful crowdfunding projects"],
      ],
    },
    work: {
      kicker: "(02) Selected Work",
      title: "Cases where visual judgment changed the output.",
      sub: "A short collection of production work where my critique loop materially moved generative quality. Tap any card for the full story.",
      items: [
        {
          id: "homo-plastikos",
          tag: "AI-Assisted Webtoon",
          year: "2023 — 2024",
          title: "Homo Plastikos",
          where: "RIDIplay  ·  Agraba (SD-based illustration tool)  ·  Serialized on Manta",
          image: "images/homo-plastikos.png",
          summary: "Stable Diffusion + LoRA + OpenPose pipeline that hit commercial-release quality and completed serialization.",
          problem: "Storyboard-faithful, character-consistent webtoon panels at production cadence — using a Stable Diffusion pipeline that wasn't yet trusted for commercial release.",
          approach: "Built and tuned LoRAs from hand-drawn references, locked character faces with checkpoints + LoRA stacks, and used OpenPose / Depth / Canny to translate storyboard intent into pose-and-camera-faithful generations. Reviewed every panel against scene direction and re-prompted or re-controlled until the read matched.",
          result: "Officially serialized and completed on Manta. Maintained character consistency, scene grammar, and panel rhythm across the run — the first time the studio shipped a generative-illustrated title at this fidelity.",
          tools: ["Stable Diffusion", "LoRA", "OpenPose", "Depth", "Canny", "ComfyUI"],
          link: { label: "Read on Manta", url: "https://manta.net/en/series/homo-plastikos?seriesId=2436" },
        },
        {
          id: "crack",
          tag: "AI Game Pipeline",
          year: "2025 — Present",
          title: "Crack — Studio Pipeline",
          where: "WRTN Technologies  ·  AI Content Quality Tutor",
          cover: "crack",
          summary: "Reviewed thousands of AI-generated illustrations per game; tightened character, expression, background and cover quality at scale.",
          problem: "An interactive AI-game platform shipping thousands of generated illustrations per title — character consistency drifting across expression and action variations, backgrounds breaking genre fit, covers losing visual hook.",
          approach: "Mapped the full pipeline end-to-end and built evaluation rubrics at each junction; traced every failure backward to the responsible stage.",
          result: "Closed feedback loops with engineers on prompt patterns, expression dictionaries (50+ emotions/situations), and genre-specific cover rules for layout, mood, typography and hook. Personal creator account on Crack reached 1,000+ followers; one work logged 112.2K+ conversations and was selected as a Crack Original.",
          tools: ["ComfyUI", "PixAI", "Midjourney", "NanoBanana", "GPT Image", "Stable Diffusion"],
          tables: [
            {
              title: "Premises",
              rows: [
                ["1", "WRTN Studio (Prompt) ships ~720 cross-genre AI Chat-Game system prompts per day."],
                ["2", "WRTN Studio (Vision) maintains an Expression Dictionary mapping 50+ human emotions/situations (laughter, tears, wailing, irritation, disbelief…) to the prompts that best express each — per AI image generator."],
                ["3", "Per-genre rules for cover layout, mood, and title-typography are codified."],
              ],
            },
            {
              title: "Illustration generation pipeline",
              rows: [
                ["1", "LLM", "Extract character info from the AI Chat-Game plan and pull each character's visual traits via LLM."],
                ["2", "LLM", "Generate a PixAI-optimized prompt that best expresses those visual traits."],
                ["3", "PixAI", "Run T2I with step-2's prompt to create the Original Image — the design baseline for that character."],
                ["4", "LLM", "From the same plan, pull each character's primary background context via LLM."],
                ["5", "GPT Image", "Apply step-3's Original Image against the per-generator entries in the Expression Dictionary (Premise 2) to produce expression and action variants."],
                ["6", "GPT Image", "Composite step-5's character images with step-4's background prompt to yield character + background scenes."],
                ["7", "Runtime", "At play time, the LLM reads the user's situation and outputs the closest matching scene as the in-game illustration."],
              ],
            },
            {
              title: "Cover generation pipeline",
              rows: [
                ["1", "LLM", "From the work's plan, take genre, hooking point, play core, and lead-character info → generate the cover prompt."],
                ["2", "Image", "Apply per-genre layout / tone / mood rules from step-1, pulling lead-character info from the illustration pipeline, to render the base cover."],
                ["3", "Image", "Run a genre-fit title-typography prompt against step-2's image to produce the final cover."],
              ],
            },
          ],
        },
        {
          id: "ridi-team",
          tag: "Team Lead",
          year: "2021 — 2022",
          title: "RIDI — Background / 3D / R&D Teams",
          where: "Team Lead, Content Production R&D",
          cover: "ridi",
          summary: "Built three new teams; +230% background-team productivity, −60% planned headcount growth, 1,008-resource shared archive.",
          problem: "Background production was the studio's bottleneck. Headcount was the default answer; quality and speed both needed lifting without that.",
          approach: "Stood up Background, 3D, and R&D teams. Built a shared archive of 1,008 reusable resources; designed a 3D character system to absorb risk when key artists were unavailable; ran the group's first internship program.",
          result: "Background productivity +230%. Planned headcount growth cut by 60%. When the archive reached the coloring team, their speed went up >40%. Two-thirds of interns shipped real projects at A-level.",
          tools: ["Process design", "3D systems", "Team leadership"],
        },
        {
          id: "ewha-mascot",
          tag: "Brand / Mascot",
          year: "University",
          title: "Ewha Womans Univ. Mascot — Whayoniz",
          where: "Grand Prize, 7th Ewha Public Relations Idea Contest",
          image: "images/whayoniz.png",
          summary: "Won a competition among 81 teams; designed Whayoniz, the official representative character of the university.",
          problem: "Design an official representative character for the university — visually distinctive, brand-coherent, deployable across PR contexts.",
          approach: "Visual Communication Design discipline: silhouette study, mark exploration, expression sheets, brand-coherent palette and proportion rules.",
          result: "Grand Prize among 81 teams. Adopted as the university's official representative mascot.",
          tools: ["Illustrator", "Photoshop"],
          link: { label: "View Whayoniz collection", url: "https://haba.myportfolio.com/whayoniz" },
        },
        {
          id: "haba-3d",
          tag: "3D Asset Studio",
          year: "2019 — 2024",
          title: "HABA — Independent 3D Asset Studio",
          where: "Sold to 716 creators  ·  KRW 100M+ cumulative",
          image: "images/haba3d.png",
          summary: "Production-ready 3D objects for webtoon, game, and animation — appearing in Lore Olympus and The Remarried Empress.",
          problem: "Webtoon and game studios needed production-ready 3D assets that behave under coloring, line-art and rendering — not generic stock.",
          approach: "Designed assets to webtoon-pipeline tolerances; iterated against real artist feedback; ran 5 successful crowdfunding rounds; held \"Best Brand\" platform recognition five years running.",
          result: "Sold to 716 creators, cumulative sales over KRW 100M, assets featured in well-known titles including Lore Olympus and The Remarried Empress.",
          tools: ["3D Modeling", "Photoshop", "Production pipelines"],
          link: { label: "Shop HABA on ACON3D", url: "https://www.acon3d.com/en/brand/012005?page=1" },
        },
        {
          id: "game-concept-art",
          tag: "Game Environment Concept Art",
          year: "2017 — 2018",
          title: "Indie Game Environment Concept Art",
          where: "University period  ·  Photoshop · oil-painting style",
          image: "images/digital-painting.jpg",
          summary: "Oil-painting-style environment concept art for an indie game — drawing and painting fundamentals applied at production scale.",
          problem: "An indie game needed atmospheric, painterly environment concept art that read clearly in-game — strong silhouette, deliberate lighting, and a hand-crafted feel rather than template-driven backgrounds.",
          approach: "Painted in Photoshop with oil-painting brushwork. Established perspective and key-light direction first, blocked silhouette and prop hierarchy, then layered material variation and atmospheric lighting passes — with deliberate brush economy in foliage and architecture.",
          result: "A body of environment art that demonstrates the drawing-and-painting fundamentals underneath everything else I do — perspective, lighting, material — including how I read AI image outputs today at the prompt level.",
          tools: ["Photoshop", "Oil-painting brushes", "Perspective", "Lighting", "Color theory"],
          link: { label: "View painting portfolio", url: "https://haba.myportfolio.com/game" },
        },
      ],
    },
    method: {
      kicker: "(03) Method",
      title: "How I teach an AI to see.",
      sub: "The Image Tutor loop, distilled. This is what I'd bring to Grok.",
      steps: [
        { n: "01", name: "Generate at scale", body: "Run the pipeline against real production briefs — not toy prompts. Volume exposes the failure modes that matter." },
        { n: "02", name: "Diagnose, don't just reject", body: "Every miss gets traced: prompt, model checkpoint, LoRA, control net, upstream LLM plan, or genre rubric? The label is only useful if the cause is named." },
        { n: "03", name: "Structure the feedback", body: "Subjective taste → repeatable criteria. Expression dictionaries (50+), genre-specific cover rules, prompt patterns per generator, character-consistency rubrics." },
        { n: "04", name: "Close the loop", body: "Hand structured feedback to engineers; revise prompts, retrain LoRAs, adjust controls, rewrite rubrics. Ship the change. Re-measure on the next batch." },
        { n: "05", name: "Reach for adjacent tools", body: "When ControlNet / OpenPose / Depth / Canny can't carry a problem, I look outside: hand-drawn LoRAs, AI ↔ 3D bridges, Photoshop-extension fixes. The pipeline isn't sacred. The output is." },
      ],
      diagram: {
        kicker: "live diagram",
        title: "AI Interactive game — mass-production pipeline",
        sub: "The system I work inside today: three premises, two pipelines. Toggle between illustration and cover generation.",
        premisesLabel: "Premises",
        tabs: { illustration: "Illustration pipeline", cover: "Cover pipeline" },
        premises: [
          { stat: "720 / day", label: "Prompt Studio", body: "Cross-genre AI Chat-Game system prompts shipped daily by WRTN Studio (Prompt)." },
          { stat: "50+", label: "Expression Dictionary", body: "Human emotions and situations — laughter, tears, wailing, irritation, disbelief — mapped per generator." },
          { stat: "Genre rules", label: "Cover playbook", body: "Per-genre rules codified for layout, mood, and title-typography." },
        ],
        illustration: [
          { tool: "LLM", title: "Extract character info", body: "Pull each character's visual traits from the AI Chat-Game plan via LLM.", out: "visual traits" },
          { tool: "LLM", title: "Compose PixAI prompt", body: "Translate those traits into a PixAI-optimized prompt.", out: "prompt" },
          { tool: "PixAI", title: "T2I — Original Image", body: "Generate the design baseline for that character.", out: "Original Image" },
          { tool: "LLM", title: "Pull background context", body: "From the same plan, extract each character's primary background traits.", out: "background prompt" },
          { tool: "GPT Image", title: "Expression × action variants", body: "Apply the Expression Dictionary against the Original Image to produce expression and action variants.", out: "character variants" },
          { tool: "GPT Image", title: "Composite scene", body: "Combine character variants with the background prompt to produce final scenes.", out: "scene image" },
          { tool: "Runtime", title: "Match in-game", body: "At play time, the LLM reads the user's situation and outputs the closest matching scene." },
        ],
        cover: [
          { tool: "LLM", title: "Compose cover prompt", body: "Pull genre, hooking point, play core, and lead-character info from the plan into a cover prompt.", out: "cover prompt" },
          { tool: "Image", title: "Render base cover", body: "Apply per-genre layout / tone / mood, with lead-character info from the illustration pipeline.", out: "base cover" },
          { tool: "Image", title: "Title typography", body: "Run a genre-fit title-typography prompt against the base cover to produce the final cover.", out: "final cover" },
        ],
      },
      feedback: {
        kicker: "before / after",
        title: "Same pipeline. One round of structured feedback.",
        sub: "Crack is a Korean subculture platform — outputs need to read as Japanese-subculture anime, not North-American illustration. Below: the same four covers, batch 1 (before my feedback) vs. batch 2 (after). The pipeline didn't change. The diagnosis did.",
        beforeLabel: "Batch 1  ·  Before feedback",
        afterLabel: "Batch 2  ·  After feedback",
        feedbackLabel: "Structured feedback",
        ctaPrev: "← Prev",
        ctaNext: "Next →",
        works: [
          { id: "A", title: "If the Head of Household Rewrites the Code of the Murim", before: "images/method/before-A.webp", after: "images/method/after-A.png" },
          { id: "B", title: "Even If Everyone Forgets, Only the Duke Remembers", before: "images/method/before-B.webp", after: "images/method/after-B.gif" },
          { id: "C", title: "Si-Geom-Haeng (詩劍行)", before: "images/method/before-C.webp", after: "images/method/after-C.png" },
          { id: "D", title: "When the Fallen Sect's Disciple Debated the Tao Anonymously", before: "images/method/before-D.webp", after: "images/method/after-D.png" },
        ],
        diagnosis: "Reads as North-American illustration: thin clean lines, low contrast, oversized eyes, teal palette, generic \"cute\" finish. Wrong cultural register for Crack.",
        outcome: "Reads as Japanese-subculture anime: dense rendering, dramatic value range, painterly hair, warmer light, ornament density. Cover-grade.",
        notes: [
          { n: "01", h: "Right model for the register", b: "PixAI is the strongest model for anime-subculture rendering (PixAI > GPT > NanoBanana). Reroute cover generation so PixAI produces both the Original Image and the cover — instead of GPT/NanoBanana off the Original." },
          { n: "02", h: "Genre-correct checkpoint", b: "Apply coco-Illustrious-NoobXL-Style — a checkpoint tuned for Japanese-subculture bishōjo rendering." },
          { n: "03", h: "+7 LoRAs for finish", b: "Stack 7 LoRAs targeting the specific finish: hair sheen, eye structure, lighting falloff, ornament density — the things that separate \"AI-anime\" from \"cover-grade anime.\"" },
          { n: "04", h: "Negative-prompt the wrong register", b: "Negative-prompt the North-American tells: thin lines, clear lines, low contrast, big eyes, extremely cute, teals. Push the model away from the default it was over-trained on." },
        ],
      },
    },
    experience: {
      kicker: "(04) Experience",
      title: "A timeline of building, leading, and tutoring.",
      items: [
        { when: "Sep 2025 — Present", where: "WRTN Technologies", role: "Product Manager / AI Content Quality Tutor", loc: "Seoul, KR",
          bullets: [
            "Joined Crack, an AI text-game platform; later worked with the Studio Team on a large-scale AI content production pipeline.",
            "Reviewed and taught AI outputs across both image and prompt quality so results could meet or exceed human-created standards.",
            "Worked as Image Tutor and Prompt Tutor — iterative critique, QC, and improvement feedback.",
            "Used ComfyUI, Stable Diffusion, PixAI, Midjourney, NanoBanana, GPT Image in production and evaluation.",
          ]},
        { when: "Feb 2025 — Aug 2025", where: "Lucidlab", role: "PM, Head of Planning & Operations", loc: "Seoul, KR",
          bullets: [
            "Led end-to-end product planning and operations for the paid messaging service \"Private Chat.\"",
            "Planned the LLM-based interactive game \"Talktory\" — concept, IA, UX flow, QA, and launch prep.",
            "Drove metrics-based iteration, BM design, IR materials, TIPS performance-testing docs, patent-claim drafting.",
            "Talktory won Grand Prize at the Seongnam Startup Competition.",
          ]},
        { when: "Aug 2023 — Mar 2024", where: "RIDIplay", role: "Product Manager, Agraba", loc: "Seoul, KR",
          bullets: [
            "Led product planning for Agraba — a Stable-Diffusion-based generative AI illustration tool for webtoon production.",
            "Collaborated with AI R&D, design, and QA teams to define functions, workflows, and production usability.",
            "Created and tested webtoon-generation workflows using Stable Diffusion, LoRA, OpenPose.",
            "Contributed to Homo Plastikos — officially serialized and completed on Manta.",
          ]},
        { when: "Mar 2023 — Jun 2023", where: "Antler Korea", role: "Co-founder, CPO — Cliwant", loc: "Seoul, KR",
          bullets: [
            "Selected as a founder in Antler Korea's 2nd cohort.",
            "Co-founder and CPO of Cliwant — an AI SaaS service for RFP analysis. Passed Pre-IC.",
          ]},
        { when: "May 2021 — Nov 2022", where: "RIDI", role: "Team Lead — Content Production R&D / 3D / Background", loc: "Seoul, KR",
          bullets: [
            "Built and managed three new teams: Background, 3D, and Content Production R&D.",
            "Background productivity +230%; planned headcount growth cut by 60%.",
            "Built a shared archive of 1,008 resources — coloring team speed +40% on adoption.",
            "Designed a 3D character system to absorb serialization risk when key artists were unavailable.",
            "Led the group's first internship program — 2/3 of interns reached production-ready performance.",
          ]},
        { when: "Jan 2019 — Dec 2024", where: "HABA", role: "Independent 3D Asset Creator & Seller", loc: "South Korea",
          bullets: [
            "Planned, created, and sold 3D object assets for webtoon, game, and animation production.",
            "Sold to 716 creators; cumulative sales over KRW 100M.",
            "Completed 5 successful crowdfunding projects.",
            "Assets appeared in Lore Olympus, The Remarried Empress, and others.",
            "Maintained \"Best Brand\" platform recognition five years running.",
          ]},
      ],
    },
    creator: {
      kicker: "(05) Creator Presence",
      title: "I publish too. I know what shipping feels like.",
      items: [
        { platform: "POSTYPE", handle: "@smyth-studio", url: "https://www.postype.com/user/collections/18480711", note: "Officially verified creator for AI image and AI chat-game creation." },
        { platform: "Crack by WRTN", handle: "치즈달", url: "https://share.crack.wrtn.ai/pl5mt37", note: "1,000+ followers. \"화나지 마세요 작가님\" — 112.2K+ conversations, selected as Crack Original." },
        { platform: "LinkedIn", handle: "in/hakyung-oh", url: "https://www.linkedin.com/in/hakyung-oh/", note: "Connect for AI-image-pipeline, image-tutoring, and visual-QA work." },
      ],
    },
    edu: {
      kicker: "(06) Education & Awards",
      school: "Ewha Womans University",
      degree: "BFA, Visual Communication Design — Seoul, South Korea",
      eduNote: "Designed the university's official representative mascot character after winning a design competition among 81 teams.",
      awards: ["Grand Prize — 7th Ewha Public Relations Idea Contest", "OPIc IH (English)", "JLPT N2 (Japanese)"],
    },
    contact: {
      kicker: "(07) Contact",
      title: "Let's teach AI to see, together.",
      body: "I'm open to AI-image-tutor, visual-QA, image-pipeline, and consulting roles. xAI in particular: I've already done the core work of an Image Tutor — review, diagnose, label, structure, ship. Happy to walk through any case study live.",
      email: "creator@smyth.world",
      phone: "+82-10-2908-3752",
      linkedin: "linkedin.com/in/hakyung-oh",
      cta: "Email Kaylee",
      cta2: "Download résumé",
    },
    footer: "© 2026 Kaylee (Hakyoung) Oh  ·  Designed for AI hiring teams who care about visual judgment.",
    modal: { problem: "Problem", approach: "Approach", result: "Result", visit: "Visit" },
  },

  ko: {
    nav: ["작업", "방법론", "경력", "소개", "연락"],
    navLabels: { work: "작업", method: "방법론", experience: "경력", about: "소개", contact: "연락" },
    hero: {
      eyebrow: "AI Image Tutor  ·  AI Visual Content Specialist",
      nameFirst: "Kaylee", nameLast: "Oh", nameScript: "Hakyoung Oh",
      tagline: ["저는 단순한 AI", "이미지 크리에이터가 아닙니다."],
      taglineAccent: "AI에게 '보는 법'을 가르칩니다.",
      sub: "프로덕션 스케일의 시각 판단력을 생성형 파이프라인에 연결합니다 — 이미지가 왜 실패했는지 진단하고, 그 진단을 프롬프트·모델·툴 단위의 개선으로 환원합니다.",
      meta: [["거주", "서울"], ["오픈 포지션", "xAI Image Tutor"], ["분야 활동", "2023 ~"]],
      cta: "주요 작업 보기",
      cta2: "이력서 (PDF) 다운로드",
    },
    marquee: ["Stable Diffusion","ComfyUI","LoRA","OpenPose","ControlNet","PixAI","Midjourney","NanoBanana","GPT Image","Photoshop","Figma","Notion"],
    about: {
      kicker: "(01) 소개",
      title: "아티스트의 시선과 엔지니어링 리터러시를 함께.",
      body: [
        "저는 시각 판단과 AI 이미지 생성이 만나는 자리에서 일합니다. Stable Diffusion이 대중화된 직후인 2023년부터 Image Tutor / QA 스페셜리스트로서 AI 어시스티드 웹툰·게임 콘텐츠 파이프라인에 참여해 왔습니다.",
        "일러스트레이터는 흔하고, AI 이미지 크리에이터도 점점 흔해지고 있습니다. 정작 드문 사람은 — 프로덕션 스케일에서 생성 결과를 평가하고, 왜 실패했는지 원인을 진단하고, 그 진단을 프롬프트·모델·컨트롤·워크플로우 단위의 구조화된 피드백으로 번역할 수 있는 사람입니다.",
        "직접 비주얼 제품을 팔아보고, 그것으로 매출을 만들고, 콘텐츠 조직 안에서 제작팀을 리드해왔습니다. 그래서 \"이거 너무 북미 카툰 같아요, 일본 애니에 가깝게 가야 합니다\" 같은 피드백을 받았을 때 — 그 차이를 구체적이고 반복 가능한 프롬프트·파이프라인 레벨의 기준으로 분해할 수 있습니다.",
      ],
      stats: [
        ["112.2K+", "단일 AI 게임작 누적 대화"],
        ["716", "내 3D 에셋을 구매한 크리에이터"],
        ["1,008", "RIDI에서 구축한 공유 아카이브"],
        ["230%", "RIDI 배경팀 생산성 향상"],
        ["50+", "표현 사전에 정의된 감정"],
        ["5", "성공한 크라우드펀딩 프로젝트"],
      ],
    },
    work: {
      kicker: "(02) 주요 작업",
      title: "시각 판단이 결과물을 바꾼 케이스들.",
      sub: "비평 루프가 생성 품질을 실제로 끌어올린 프로덕션 작업의 짧은 모음. 각 카드를 클릭하면 전체 스토리를 볼 수 있습니다.",
      items: [
        {
          id: "homo-plastikos",
          tag: "AI 어시스티드 웹툰",
          year: "2023 — 2024",
          title: "Homo Plastikos",
          where: "RIDIplay  ·  Agraba (SD 기반 일러스트 툴)  ·  Manta 연재",
          image: "images/homo-plastikos.png",
          summary: "Stable Diffusion + LoRA + OpenPose 파이프라인으로 상업 출시 품질에 도달하고 연재 완결.",
          problem: "스토리보드 충실도와 캐릭터 일관성을 유지한 채, 아직 상업용으로 검증되지 않았던 SD 파이프라인을 프로덕션 속도로 돌려야 했습니다.",
          approach: "수기 레퍼런스로부터 LoRA를 빌드·튜닝하고, 체크포인트 + LoRA 스택으로 캐릭터 페이스를 고정. OpenPose / Depth / Canny로 스토리보드의 포즈와 카메라를 그대로 옮겼습니다. 모든 컷을 디렉션 기준으로 검토하고 의도한 리딩이 나올 때까지 재프롬프트·재컨트롤.",
          result: "Manta에서 정식 연재 및 완결. 캐릭터 일관성, 컷 그래머, 페이지 리듬을 끝까지 유지 — 스튜디오 최초로 이 정도 충실도의 생성형 일러스트 작품을 출고.",
          tools: ["Stable Diffusion", "LoRA", "OpenPose", "Depth", "Canny", "ComfyUI"],
          link: { label: "Manta에서 보기", url: "https://manta.net/en/series/homo-plastikos?seriesId=2436" },
        },
        {
          id: "crack",
          tag: "AI 게임 파이프라인",
          year: "2025 — 현재",
          title: "Crack — 스튜디오 파이프라인",
          where: "WRTN Technologies  ·  AI Content Quality Tutor",
          cover: "crack",
          summary: "한 게임당 수천 장의 AI 일러스트를 검토 — 캐릭터·표정·배경·커버 품질을 스케일에서 단단하게 만듭니다.",
          problem: "게임 한 편당 수천 장을 출고하는 인터랙티브 AI 게임 플랫폼. 표정·액션 변형마다 캐릭터 일관성이 흔들리고, 배경이 장르를 깨고, 커버에서 비주얼 후크가 사라지는 문제.",
          approach: "전체 파이프라인을 매핑하고 각 분기마다 평가 루브릭을 만들어, 실패 케이스를 책임 단계까지 역추적했습니다.",
          result: "엔지니어와 함께 프롬프트 패턴, 50+ 감정·상황 표현 사전, 장르별 커버 룰(레이아웃·무드·타이포·후크)을 정착. 개인 Crack 계정 팔로워 1,000+, 한 작품은 112.2K+ 대화 기록과 함께 Crack Original 선정.",
          tools: ["ComfyUI", "PixAI", "Midjourney", "NanoBanana", "GPT Image", "Stable Diffusion"],
          tables: [
            {
              title: "전제 사항",
              rows: [
                ["1", "WRTN Studio (Prompt) 파트는 하루에 720개의 다른 장르의 AI Chat Game System Prompt를 생산."],
                ["2", "WRTN Studio (Vision) 파트는 웃음·눈물·오열·짜증·어이없음 등 50+ 감정 및 상황에 대해, AI Image Generator 별로 가장 잘 표현해내는 프롬프트들을 정리한 'Expression Dictionary'를 운영."],
                ["3", "작품의 장르별로 적절한 표지 레이아웃, 무드, 타이틀 표현 방법이 정리되어 있음."],
              ],
            },
            {
              title: "삽화 생성 과정",
              rows: [
                ["1", "LLM", "AI Chat Game 기획서에서 등장 캐릭터 정보를 추출해, 캐릭터의 외형 특징을 LLM으로 받아옴."],
                ["2", "LLM", "받아온 외형 특징을 PixAI로 가장 잘 표현할 수 있는 프롬프트 생성."],
                ["3", "PixAI", "2번 프롬프트로 T2I를 거쳐 인물 디자인의 기준이 되는 Original Image 생성."],
                ["4", "LLM", "기획서에서 캐릭터별 주 활동 배경 정보·특징을 LLM으로 받아옴."],
                ["5", "GPT Image", "3번의 Original Image에 전제 2번의 Expression Dictionary를 매칭, 다양한 표정·액션의 인물 이미지 생성."],
                ["6", "GPT Image", "5번 결과 이미지에 4번의 배경 프롬프트를 합성해 캐릭터 + 배경 장면 이미지 생성."],
                ["7", "런타임", "유저가 AI Chat Game 진행 시 마주치는 상황을 LLM이 파악, 가장 유사한 이미지를 삽화로 출력."],
              ],
            },
            {
              title: "표지 생성 과정",
              rows: [
                ["1", "LLM", "기획서로부터 장르 / Hooking Point / Play Core / 중심 인물 정보를 받아 표지 프롬프트 생성."],
                ["2", "Image", "1번에서 받은 장르의 표지 특징(레이아웃·톤앤무드·프롬프트)을 적용하고, 중심 인물 정보를 '삽화 생성 과정'에서 받아 바탕 이미지 생성."],
                ["3", "Image", "1번 장르 특징에 맞는 타이틀 타이포그래피 프롬프트를 2번 이미지와 함께 돌려 최종 표지 생성."],
              ],
            },
          ],
        },
        {
          id: "ridi-team",
          tag: "팀 리드",
          year: "2021 — 2022",
          title: "RIDI — 배경 / 3D / R&D",
          where: "팀 리드, 콘텐츠 프로덕션 R&D",
          cover: "ridi",
          summary: "신규 3개 팀 구축. 배경팀 생산성 +230%, 채용 계획 −60%, 1,008개 리소스 공유 아카이브.",
          problem: "배경 제작이 스튜디오의 병목. 헤드카운트 증원이 디폴트 답이지만, 그 답 없이 품질과 속도를 올려야 했습니다.",
          approach: "배경팀 / 3D팀 / R&D팀을 신설. 1,008개 리소스의 공유 아카이브 구축. 핵심 작가 부재 시 리스크를 흡수하는 3D 캐릭터 시스템 설계. 그룹 첫 인턴십 운영.",
          result: "배경팀 생산성 +230%. 계획된 채용 증가 60% 절감. 채색팀에 적용 시 작업 속도 +40%. 인턴 2/3가 실제 프로젝트를 A 레벨로 완수.",
          tools: ["프로세스 디자인", "3D 시스템", "팀 리더십"],
        },
        {
          id: "ewha-mascot",
          tag: "브랜드 / 마스코트",
          year: "대학 시절",
          title: "이화여대 공식 마스코트 — 화연이",
          where: "제7회 이화홍보 아이디어 공모전 대상",
          image: "images/whayoniz.png",
          summary: "81개 팀 중 대상 — 이화여대의 공식 대표 캐릭터 '화연이' 디자인.",
          problem: "대학의 공식 대표 캐릭터를 디자인하라 — 시각적으로 변별력 있고, 브랜드와 일관되며, 다양한 PR 맥락에 배포 가능한.",
          approach: "시각 디자인 본령: 실루엣 연구, 마크 탐색, 표정 시트, 브랜드와 일관된 팔레트·비례 룰.",
          result: "81개 팀 중 대상. 대학의 공식 대표 마스코트로 채택.",
          tools: ["Illustrator", "Photoshop"],
          link: { label: "화연이 컬렉션 보기", url: "https://haba.myportfolio.com/whayoniz" },
        },
        {
          id: "haba-3d",
          tag: "3D 에셋 스튜디오",
          year: "2019 — 2024",
          title: "HABA — 독립 3D 에셋 스튜디오",
          where: "716명 크리에이터 구매  ·  누적 1억+",
          image: "images/haba3d.png",
          summary: "Lore Olympus, 재혼황후 등에 사용된 프로덕션 레디 3D 오브젝트 스튜디오.",
          problem: "웹툰·게임 스튜디오는 채색·선화·렌더링 파이프라인을 통과하는 \"진짜\" 프로덕션 3D 에셋이 필요했습니다 — 일반 스톡으로는 부족.",
          approach: "웹툰 파이프라인의 허용 오차에 맞춰 설계. 실제 작가 피드백 위에서 반복. 5회 크라우드펀딩 성공. 5년 연속 플랫폼 \"Best Brand\" 인증.",
          result: "716명 크리에이터에게 판매, 누적 1억 원 이상. Lore Olympus, 재혼황후 등 알려진 작품에 등장.",
          tools: ["3D 모델링", "Photoshop", "프로덕션 파이프라인"],
          link: { label: "ACON3D에서 HABA 마켓 보기", url: "https://www.acon3d.com/en/brand/012005?page=1" },
        },
        {
          id: "game-concept-art",
          tag: "게임 환경 컨셉아트",
          year: "2017 — 2018",
          title: "인디 게임 환경 컨셉아트",
          where: "대학 시절  ·  Photoshop · 오일 페인팅 스타일",
          image: "images/digital-painting.jpg",
          summary: "인디 게임의 환경 컨셉아트 — 오일 페인팅 풍의 페인터리한 라이팅 중심 배경 원화. 드로잉/페인팅 펀더멘털을 프로덕션 스케일에 적용.",
          problem: "인디 게임 파이프라인에 인게임에서 또렷이 읽히는 환경 컨셉아트가 필요했습니다 — 강한 실루엣, 의도된 라이팅, 그리고 템플릿 느낌이 아닌 핸드크래프트 무드.",
          approach: "Photoshop의 오일 페인팅 브러시로 페인팅. 투시와 키 라이트 방향을 먼저 잡고, 실루엣과 소품 위계를 블로킹한 뒤, 재질 편차와 분위기 라이팅을 레이어로 쌓았습니다. 식생·건축에서는 의도적인 브러시 절제.",
          result: "이후 제가 하는 모든 작업의 바탕인 드로잉·페인팅 기본기 — 투시·라이팅·재질 — 를 보여주는 시리즈. AI 이미지 출력을 프롬프트 레벨에서 읽어내는 시선의 토대이기도 합니다.",
          tools: ["Photoshop", "오일 페인팅 브러시", "투시", "라이팅", "색채 이론"],
          link: { label: "페인팅 포트폴리오 보기", url: "https://haba.myportfolio.com/game" },
        },
      ],
    },
    method: {
      kicker: "(03) 방법론",
      title: "AI에게 '보는 법'을 가르치는 법.",
      sub: "Image Tutor 루프를 압축한 5단계. xAI / Grok에 그대로 들고 들어갈 수 있습니다.",
      steps: [
        { n: "01", name: "스케일로 생성", body: "장난감 프롬프트가 아니라 실제 프로덕션 브리프로 파이프라인을 돌립니다." },
        { n: "02", name: "단순 거절이 아닌 진단", body: "모든 미스에 원인 추적: 프롬프트 / 체크포인트 / LoRA / 컨트롤넷 / 상위 LLM 기획 / 장르 루브릭 — 원인이 명명되지 않은 라벨은 쓸모없습니다." },
        { n: "03", name: "피드백을 구조화", body: "주관적 취향 → 반복 가능한 기준. 50+ 감정의 표현 사전, 장르별 커버 룰, 생성기별 프롬프트 패턴, 캐릭터 일관성 루브릭." },
        { n: "04", name: "루프를 닫기", body: "엔지니어에게 구조화된 피드백 인계 → 프롬프트 수정, LoRA 재학습, 컨트롤 조정, 루브릭 갱신. 변경 출고. 다음 배치에서 재측정." },
        { n: "05", name: "인접 도구로 손 뻗기", body: "ControlNet / OpenPose / Depth / Canny가 못 푸는 문제는 바깥에서 풉니다 — 수기 LoRA, AI ↔ 3D 브릿지, Photoshop 익스텐션. 파이프라인은 신성하지 않습니다. 결과물이 신성합니다." },
      ],
      diagram: {
        kicker: "라이브 다이어그램",
        title: "AI Interactive game — 대량생산 파이프라인",
        sub: "제가 지금 일하고 있는 시스템 — 3개의 전제, 2개의 파이프라인. 삽화와 표지 생성을 토글로 비교해 보세요.",
        premisesLabel: "전제 사항",
        tabs: { illustration: "삽화 생성 파이프라인", cover: "표지 생성 파이프라인" },
        premises: [
          { stat: "720개 / 일", label: "Prompt 파트", body: "WRTN Studio Prompt 파트가 매일 출고하는 다른 장르의 AI Chat Game System Prompt." },
          { stat: "50+", label: "Expression Dictionary", body: "웃음·눈물·오열·짜증·어이없음 등 인간 감정/상황을, AI Image Generator 별로 가장 잘 표현하는 프롬프트로 정리." },
          { stat: "장르별 룰", label: "표지 플레이북", body: "작품 장르별로 적합한 표지 레이아웃·무드·타이틀 표현 방법이 정리됨." },
        ],
        illustration: [
          { tool: "LLM", title: "캐릭터 정보 추출", body: "AI Chat Game 기획서에서 캐릭터의 외형 특징을 LLM으로 받아옴.", out: "외형 특징" },
          { tool: "LLM", title: "PixAI 프롬프트 생성", body: "외형 특징을 PixAI로 가장 잘 표현할 수 있는 프롬프트로 변환.", out: "프롬프트" },
          { tool: "PixAI", title: "T2I — Original Image", body: "프롬프트로 T2I를 거쳐 인물 디자인의 기준이 되는 Original Image 생성.", out: "Original Image" },
          { tool: "LLM", title: "배경 컨텍스트 추출", body: "같은 기획서에서 캐릭터별 주 활동 배경의 정보·특징을 받아옴.", out: "배경 프롬프트" },
          { tool: "GPT Image", title: "표정·액션 변형", body: "Expression Dictionary를 Original Image에 매칭해 다양한 표정·액션의 인물 이미지 생성.", out: "캐릭터 변형" },
          { tool: "GPT Image", title: "장면 합성", body: "캐릭터 변형 + 배경 프롬프트를 합쳐 캐릭터 + 배경 장면 이미지 생성.", out: "장면 이미지" },
          { tool: "런타임", title: "인게임 매칭", body: "플레이 시점에 LLM이 유저의 상황을 읽고 가장 유사한 장면을 삽화로 출력." },
        ],
        cover: [
          { tool: "LLM", title: "표지 프롬프트 생성", body: "기획서로부터 장르 / Hooking Point / Play Core / 중심 인물 정보를 받아 표지 프롬프트 작성.", out: "표지 프롬프트" },
          { tool: "Image", title: "바탕 이미지 생성", body: "장르의 표지 특징(레이아웃·톤앤무드)을 적용, 중심 인물 정보를 삽화 파이프라인에서 받아 바탕 이미지 렌더.", out: "바탕 이미지" },
          { tool: "Image", title: "타이틀 타이포그래피", body: "장르 특징에 맞는 타이틀 타이포그래피 프롬프트를 바탕 이미지와 함께 돌려 최종 표지 생성.", out: "최종 표지" },
        ],
      },
      feedback: {
        kicker: "before / after",
        title: "같은 파이프라인. 단 한 번의 구조화된 피드백.",
        sub: "Crack은 한국의 서브컬처 플랫폼 — 결과물은 북미풍 일러스트가 아닌 일본 서브컬처 아니메풍으로 읽혀야 합니다. 아래는 같은 4개 작품의 표지, 1차 배치(피드백 전) vs. 2차 배치(피드백 후). 파이프라인은 그대로. 바뀐 건 진단입니다.",
        beforeLabel: "1차 배치  ·  피드백 전",
        afterLabel: "2차 배치  ·  피드백 후",
        feedbackLabel: "구조화된 피드백",
        ctaPrev: "← 이전",
        ctaNext: "다음 →",
        works: [
          { id: "A", title: "소가주가 무림의 법도를 다시 쓰면", before: "images/method/before-A.webp", after: "images/method/after-A.png" },
          { id: "B", title: "모두가 잊어도 공작만은 기억한다", before: "images/method/before-B.webp", after: "images/method/after-B.gif" },
          { id: "C", title: "시검행 (詩劍行)", before: "images/method/before-C.webp", after: "images/method/after-C.png" },
          { id: "D", title: "멸문 제자가 익명으로 도를 논했더니", before: "images/method/before-D.webp", after: "images/method/after-D.png" },
        ],
        diagnosis: "북미풍 일러스트 특징이 강함: 얇고 깔끔한 선, 낮은 콘트라스트, 과장된 큰 눈, 청록 위주 팔레트, 통상적인 '귀여운' 마감. Crack의 문화적 코드와 맞지 않음.",
        outcome: "일본 서브컬처 아니메풍으로 읽힘: 밀도 높은 렌더링, 극적인 명암, 회화적 머리카락, 따뜻한 광원, 장식 밀도. 표지급 퀄리티.",
        notes: [
          { n: "01", h: "코드에 맞는 모델로 재배선", b: "아니메 서브컬처 렌더링에는 PixAI가 가장 강함 (PixAI > GPT > NanoBanana). 기존엔 Original Image만 PixAI, 표정·액션은 NanoBanana — 표지 생성 공정을 바꿔 Original Image를 뽑을 때 PixAI가 표지용 이미지까지 같이 뽑도록 재구성." },
          { n: "02", h: "장르 적합 체크포인트", b: "coco-Illustrious-NoobXL-Style 적용 — 일본향 서브컬처 미소녀 렌더링에 튜닝된 체크포인트." },
          { n: "03", h: "+7 LoRA로 마감 정렬", b: "특정 마감 — 머리카락 광택, 눈 구조, 광원 falloff, 장식 밀도 — 를 잡아주는 LoRA 7종 스택. 'AI 아니메'와 '표지급 아니메'를 가르는 디테일." },
          { n: "04", h: "잘못된 코드를 역 프롬프팅", b: "북미풍 일러스트의 강한 특징을 negative prompt로 차단: thin lines, clear lines, low contrast, big eyes, extremely cute, teals. 모델이 과학습된 디폴트로부터 멀어지게." },
        ],
      },
    },
    experience: {
      kicker: "(04) 경력",
      title: "구축하고 · 리드하고 · 가르쳐 온 타임라인.",
      items: [
        { when: "2025.09 — 현재", where: "WRTN Technologies", role: "Product Manager / AI Content Quality Tutor", loc: "서울",
          bullets: [
            "AI 텍스트 게임 플랫폼 Crack 합류. 이후 Studio Team과 대규모 AI 콘텐츠 프로덕션 파이프라인 협업.",
            "이미지 품질 + 프롬프트 품질 양쪽에서 AI 출력을 검토·교습 — 사람 제작 기준을 충족·초과하도록.",
            "Image Tutor / Prompt Tutor 역할 — 반복 비평, QC, 개선 피드백.",
            "프로덕션 및 평가 워크플로우에 ComfyUI, SD, PixAI, Midjourney, NanoBanana, GPT Image 사용.",
          ]},
        { when: "2025.02 — 2025.08", where: "Lucidlab", role: "PM, Head of Planning & Operations", loc: "서울",
          bullets: [
            "유료 메시징 서비스 \"Private Chat\" E2E 기획·운영.",
            "LLM 기반 인터랙티브 게임 \"Talktory\" 컨셉 → IA → UX 플로우 → QA → 런칭 준비.",
            "지표 기반 이터레이션, BM 디자인, IR 자료, TIPS 검증 문서, 특허 청구항 작성.",
            "Talktory — 성남 스타트업 경진대회 대상 수상.",
          ]},
        { when: "2023.08 — 2024.03", where: "RIDIplay", role: "Product Manager, Agraba", loc: "서울",
          bullets: [
            "웹툰 제작용 SD 기반 생성 일러스트 툴 Agraba 제품 기획 리드.",
            "AI R&D · 디자인 · QA와 함께 기능·워크플로우·프로덕션 사용성 정의.",
            "SD / LoRA / OpenPose로 직접 웹툰 생성 워크플로우 제작·검증.",
            "Manta 정식 연재·완결작 Homo Plastikos 기여.",
          ]},
        { when: "2023.03 — 2023.06", where: "Antler Korea", role: "Co-founder, CPO — Cliwant", loc: "서울",
          bullets: [
            "Antler Korea 2기 창업자 선발.",
            "AI SaaS 기반 RFP 분석 서비스 Cliwant 공동창업·CPO. Pre-IC 통과.",
          ]},
        { when: "2021.05 — 2022.11", where: "RIDI", role: "팀 리드 — Content Production R&D / 3D / 배경", loc: "서울",
          bullets: [
            "신규 3개 팀(배경 / 3D / R&D) 구축·운영.",
            "배경팀 생산성 +230%, 계획된 채용 증가 60% 절감.",
            "1,008개 리소스 공유 아카이브 구축 — 채색팀 작업 속도 +40%.",
            "핵심 작가 부재 시 연재 리스크를 줄이는 3D 캐릭터 시스템 설계.",
            "그룹 첫 인턴십 운영 — 인턴 2/3가 프로덕션 레디 수준 도달.",
          ]},
        { when: "2019.01 — 2024.12", where: "HABA", role: "독립 3D 에셋 크리에이터·셀러", loc: "한국",
          bullets: [
            "웹툰·게임·애니메이션 프로덕션용 3D 오브젝트 기획·제작·판매.",
            "716명 크리에이터에게 판매, 누적 1억 원 이상.",
            "5회 크라우드펀딩 성공.",
            "Lore Olympus, 재혼황후 등 알려진 작품에 에셋 등장.",
            "5년 연속 플랫폼 \"Best Brand\" 인증.",
          ]},
      ],
    },
    creator: {
      kicker: "(05) Creator Presence",
      title: "직접 출고합니다. 출고가 어떤 감각인지 압니다.",
      items: [
        { platform: "POSTYPE", handle: "@smyth-studio", url: "https://www.postype.com/user/collections/18480711", note: "AI 이미지 / AI 챗 게임 공식 인증 크리에이터." },
        { platform: "Crack by WRTN", handle: "치즈달", url: "https://share.crack.wrtn.ai/pl5mt37", note: "팔로워 1,000+. \"화나지 마세요 작가님\" — 112.2K+ 대화, Crack Original 선정." },
        { platform: "LinkedIn", handle: "in/hakyung-oh", url: "https://www.linkedin.com/in/hakyung-oh/", note: "AI 이미지 파이프라인 / 이미지 튜터링 / 비주얼 QA 관련 연결 환영." },
      ],
    },
    edu: {
      kicker: "(06) 학력 & 수상",
      school: "이화여자대학교",
      degree: "BFA, 시각디자인 — 서울",
      eduNote: "81개 팀 중 디자인 공모전 대상 수상 후 대학의 공식 대표 마스코트 캐릭터 디자인.",
      awards: ["대상 — 제7회 이화홍보 아이디어 공모전", "OPIc IH (영어)", "JLPT N2 (일본어)"],
    },
    contact: {
      kicker: "(07) 연락",
      title: "AI에게 '보는 법'을, 함께 가르쳐요.",
      body: "AI 이미지 튜터, 비주얼 QA, 이미지 파이프라인, 컨설팅 포지션에 열려 있습니다. xAI에 특히: 이미지 튜터의 핵심 업무 — 검토, 진단, 라벨, 구조화, 출고 — 를 이미 해 왔습니다.",
      email: "creator@smyth.world",
      phone: "+82-10-2908-3752",
      linkedin: "linkedin.com/in/hakyung-oh",
      cta: "이메일 보내기",
      cta2: "이력서 다운로드",
    },
    footer: "© 2026 Kaylee (Hakyoung) Oh  ·  시각 판단을 중요하게 보는 AI 채용팀을 위한 사이트.",
    modal: { problem: "문제", approach: "접근", result: "결과", visit: "바로가기" },
  },
};

window.CONTENT = CONTENT;
